### ISSUE TITLE
 Exchange from MIOTA token to SMR

### ISSUE THREAD

**Issue by Kirillich560** [TangleSwap/feedback#1]
### Contact details

lolofre560@gmail.com

### What happened?

I expected a correct swap to occur, but a constant error occurs. Maybe it has something to do with a mistake in the contract.

What is the point?
1. I swapped from SMR to MIOTA. Everything went flawlessly
2. Then I tried to swap back from MIOTA to SMR
3. And received a failed transaction
4. I am attaching the wallet and hash of the transaction. one of many

my wallet: 0xb470759be166E48aa7BBfeBA43B345ac8CafF8Ee

tx: 0xafbaebc549c7b051e0dad0d3bbb513c073cd845ab88f221d70f30d582e38e5d4

I have attached a screenshot to illustrate the issue.
![image](https://github.com/TangleSwap/feedback/assets/80064034/a34b4c09-c499-4c81-a50f-411378f8a8db)
![image](https://github.com/TangleSwap/feedback/assets/80064034/403337e6-f2cd-44bd-b6bb-de346a1d9693)

**Comment by PilotSevane** [comment]
Thanks for reporting! Upon checking the [Explorer](https://explorer.evm.testnet.shimmer.network/tx/0xafbaebc549c7b051e0dad0d3bbb513c073cd845ab88f221d70f30d582e38e5d4), it seems like the ShimmerEVM RPC's nonce issue caused the failing tx -- this is a known bug to the IOTA Foundation and should be solved with their next upcoming upgrade.

Will close this issue for now since it's not for TangleSwap to solve, but feel free to re-open if needed!
